//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class BusyIndicatorPageResources
{
    private static System.Resources.ResourceManager? resourceMan;

    private static System.Globalization.CultureInfo? resourceCulture;

    internal BusyIndicatorPageResources()
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new System.Resources.ResourceManager(
            "MyNet.Avalonia.Showcase.Resources.BusyIndicatorPageResources",
            typeof(BusyIndicatorPageResources).Assembly);

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Globalization.CultureInfo Culture
    {
        get => resourceCulture!;
        set => resourceCulture = value;
    }

    internal static string PanelTitle => ResourceManager.GetString(nameof(PanelTitle), resourceCulture)!;

    internal static string PanelDescription => ResourceManager.GetString(nameof(PanelDescription), resourceCulture)!;

    internal static string StartButton => ResourceManager.GetString(nameof(StartButton), resourceCulture)!;

    internal static string TestClickButton => ResourceManager.GetString(nameof(TestClickButton), resourceCulture)!;

    internal static string TestClickCountLabel => ResourceManager.GetString(nameof(TestClickCountLabel), resourceCulture)!;

    internal static string ThemePreviewContent => ResourceManager.GetString(nameof(ThemePreviewContent), resourceCulture)!;

    internal static string DefaultBusyMessage => ResourceManager.GetString(nameof(DefaultBusyMessage), resourceCulture)!;

    internal static string ServicePanelTitle => ResourceManager.GetString(nameof(ServicePanelTitle), resourceCulture)!;

    internal static string ServicePanelDescription => ResourceManager.GetString(nameof(ServicePanelDescription), resourceCulture)!;

    internal static string ServiceIndeterminateButton => ResourceManager.GetString(nameof(ServiceIndeterminateButton), resourceCulture)!;

    internal static string ServiceDeterminateButton => ResourceManager.GetString(nameof(ServiceDeterminateButton), resourceCulture)!;

    internal static string ServiceProgressionButton => ResourceManager.GetString(nameof(ServiceProgressionButton), resourceCulture)!;

    internal static string ServiceNestedButton => ResourceManager.GetString(nameof(ServiceNestedButton), resourceCulture)!;

    internal static string ServiceIndeterminateMessage => ResourceManager.GetString(nameof(ServiceIndeterminateMessage), resourceCulture)!;

    internal static string ServiceIndeterminateStepFormat => ResourceManager.GetString(nameof(ServiceIndeterminateStepFormat), resourceCulture)!;

    internal static string ServiceDeterminateMessage => ResourceManager.GetString(nameof(ServiceDeterminateMessage), resourceCulture)!;

    internal static string ServiceProgressionStep1 => ResourceManager.GetString(nameof(ServiceProgressionStep1), resourceCulture)!;

    internal static string ServiceProgressionStep2 => ResourceManager.GetString(nameof(ServiceProgressionStep2), resourceCulture)!;

    internal static string ServiceProgressionStep3 => ResourceManager.GetString(nameof(ServiceProgressionStep3), resourceCulture)!;

    internal static string ServiceProgressionStep4 => ResourceManager.GetString(nameof(ServiceProgressionStep4), resourceCulture)!;

    internal static string ServiceNestedOuter => ResourceManager.GetString(nameof(ServiceNestedOuter), resourceCulture)!;

    internal static string ServiceNestedInner => ResourceManager.GetString(nameof(ServiceNestedInner), resourceCulture)!;

    internal static string ServiceNestedInnerResume => ResourceManager.GetString(nameof(ServiceNestedInnerResume), resourceCulture)!;

    internal static string ServiceNestedResumed => ResourceManager.GetString(nameof(ServiceNestedResumed), resourceCulture)!;
}
