//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class BusyIndicatorPageResources
{
    private static System.Resources.ResourceManager? resourceMan;

    private static System.Globalization.CultureInfo? resourceCulture;

    internal BusyIndicatorPageResources()
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new System.Resources.ResourceManager(
            "MyNet.Avalonia.Showcase.Resources.BusyIndicatorPageResources",
            typeof(BusyIndicatorPageResources).Assembly);

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Globalization.CultureInfo Culture
    {
        get => resourceCulture!;
        set => resourceCulture = value;
    }

    internal static string PanelTitle => ResourceManager.GetString(nameof(PanelTitle), resourceCulture)!;

    internal static string PanelDescription => ResourceManager.GetString(nameof(PanelDescription), resourceCulture)!;

    internal static string StartButton => ResourceManager.GetString(nameof(StartButton), resourceCulture)!;

    internal static string TestClickButton => ResourceManager.GetString(nameof(TestClickButton), resourceCulture)!;

    internal static string TestClickCountLabel => ResourceManager.GetString(nameof(TestClickCountLabel), resourceCulture)!;

    internal static string ThemePreviewContent => ResourceManager.GetString(nameof(ThemePreviewContent), resourceCulture)!;

    internal static string DefaultBusyMessage => ResourceManager.GetString(nameof(DefaultBusyMessage), resourceCulture)!;
}
