//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.CardPageResources", typeof(CardPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez cliquer sur la carte..
        /// </summary>
        internal static string ClickMessage {
            get {
                return ResourceManager.GetString("ClickMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte cliquée !.
        /// </summary>
        internal static string ClickTitle {
            get {
                return ResourceManager.GetString("ClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pied de page.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En-tête.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;indicateur.
        /// </summary>
        internal static string ShowTrailing {
            get {
                return ResourceManager.GetString("ShowTrailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-titre.
        /// </summary>
        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        internal static string LayoutGallerySection {
            get {
                return ResourceManager.GetString("LayoutGallerySection", resourceCulture);
            }
        }
        
        internal static string LayoutGalleryDescription {
            get {
                return ResourceManager.GetString("LayoutGalleryDescription", resourceCulture);
            }
        }
        
        internal static string LeadingPresentationSection {
            get {
                return ResourceManager.GetString("LeadingPresentationSection", resourceCulture);
            }
        }
        
        internal static string UseCasesSection {
            get {
                return ResourceManager.GetString("UseCasesSection", resourceCulture);
            }
        }
        
        internal static string ContentOnlyExample {
            get {
                return ResourceManager.GetString("ContentOnlyExample", resourceCulture);
            }
        }
    }
}
