//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlThemeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlThemeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.ControlThemeResources", typeof(ControlThemeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string ThemeBorderCard {
            get {
                return ResourceManager.GetString("ThemeBorderCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône.
        /// </summary>
        internal static string ThemeButtonIcon {
            get {
                return ResourceManager.GetString("ThemeButtonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ThemeButtonRounded {
            get {
                return ResourceManager.GetString("ThemeButtonRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souligné.
        /// </summary>
        internal static string ThemeButtonSpinnerUnderline {
            get {
                return ResourceManager.GetString("ThemeButtonSpinnerUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactif.
        /// </summary>
        internal static string ThemeCardInteractive {
            get {
                return ResourceManager.GetString("ThemeCardInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complet.
        /// </summary>
        internal static string ThemeCarouselFull {
            get {
                return ResourceManager.GetString("ThemeCarouselFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifié.
        /// </summary>
        internal static string ThemeColorViewSimple {
            get {
                return ResourceManager.GetString("ThemeColorViewSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème par défaut.
        /// </summary>
        internal static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ThemeDropDownButtonRounded {
            get {
                return ResourceManager.GetString("ThemeDropDownButtonRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string ThemeEllipseCard {
            get {
                return ResourceManager.GetString("ThemeEllipseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton.
        /// </summary>
        internal static string ThemeExpanderButton {
            get {
                return ResourceManager.GetString("ThemeExpanderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souligné.
        /// </summary>
        internal static string ThemeFieldsUnderline {
            get {
                return ResourceManager.GetString("ThemeFieldsUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string ThemeHeaderedContentControlCard {
            get {
                return ResourceManager.GetString("ThemeHeaderedContentControlCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        internal static string ThemeHeaderedContentControlLabel {
            get {
                return ResourceManager.GetString("ThemeHeaderedContentControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        internal static string ThemeLabelBadge {
            get {
                return ResourceManager.GetString("ThemeLabelBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ThemeLabelCode {
            get {
                return ResourceManager.GetString("ThemeLabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartes.
        /// </summary>
        internal static string ThemeListBoxCards {
            get {
                return ResourceManager.GetString("ThemeListBoxCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icônes.
        /// </summary>
        internal static string ThemeListBoxIcon {
            get {
                return ResourceManager.GetString("ThemeListBoxIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicateur.
        /// </summary>
        internal static string ThemeListBoxIndicator {
            get {
                return ResourceManager.GetString("ThemeListBoxIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglets.
        /// </summary>
        internal static string ThemeListBoxTabs {
            get {
                return ResourceManager.GetString("ThemeListBoxTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chips.
        /// </summary>
        internal static string ThemeListBoxToggle {
            get {
                return ResourceManager.GetString("ThemeListBoxToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        internal static string ThemePaginationCompact {
            get {
                return ResourceManager.GetString("ThemePaginationCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ThemeProgressBarCircular {
            get {
                return ResourceManager.GetString("ThemeProgressBarCircular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicateur.
        /// </summary>
        internal static string ThemeTabControlIndicator {
            get {
                return ResourceManager.GetString("ThemeTabControlIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton icône.
        /// </summary>
        internal static string ThemeToggleButtonIcon {
            get {
                return ResourceManager.GetString("ThemeToggleButtonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ThemeToggleButtonRounded {
            get {
                return ResourceManager.GetString("ThemeToggleButtonRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatif.
        /// </summary>
        internal static string ThemeToggleSwitchAlternate {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton.
        /// </summary>
        internal static string ThemeToggleSwitchButton {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton icône.
        /// </summary>
        internal static string ThemeToggleSwitchButtonIcon {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchButtonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton circulaire.
        /// </summary>
        internal static string ThemeToggleSwitchButtonRounded {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchButtonRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intérieur.
        /// </summary>
        internal static string ThemeToggleSwitchInner {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchInner", resourceCulture);
            }
        }
    }
}
