//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogsPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogsPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.DialogsPageResources", typeof(DialogsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer le dialogue du dessus.
        /// </summary>
        internal static string CloseTopDialog {
            get {
                return ResourceManager.GetString("CloseTopDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le thème Overlay pour fermer un overlay programmatiquement..
        /// </summary>
        internal static string CloseTopRequiresOverlayTheme {
            get {
                return ResourceManager.GetString("CloseTopRequiresOverlayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue fermé via CloseAsync..
        /// </summary>
        internal static string DialogClosedProgrammatically {
            get {
                return ResourceManager.GetString("DialogClosedProgrammatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur inattendue est arrivée. Essayez encore..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci est un message d&apos;information..
        /// </summary>
        internal static string InformationMessage {
            get {
                return ResourceManager.GetString("InformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageBoxResultOptionOk {
            get {
                return ResourceManager.GetString("MessageBoxResultOptionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK - Annuler.
        /// </summary>
        internal static string MessageBoxResultOptionOkCancel {
            get {
                return ResourceManager.GetString("MessageBoxResultOptionOkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui - Non.
        /// </summary>
        internal static string MessageBoxResultOptionYesNo {
            get {
                return ResourceManager.GetString("MessageBoxResultOptionYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui - Non - Annuler.
        /// </summary>
        internal static string MessageBoxResultOptionYesNoCancel {
            get {
                return ResourceManager.GetString("MessageBoxResultOptionYesNoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun dialogue ouvert à fermer..
        /// </summary>
        internal static string NoOpenDialog {
            get {
                return ResourceManager.GetString("NoOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test des dialogues en overlay sur la page.
        /// </summary>
        internal static string OverlayDialogDescription {
            get {
                return ResourceManager.GetString("OverlayDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content dialog.
        /// </summary>
        internal static string ShowContentDialog {
            get {
                return ResourceManager.GetString("ShowContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog box.
        /// </summary>
        internal static string ShowDialogBox {
            get {
                return ResourceManager.GetString("ShowDialogBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message box.
        /// </summary>
        internal static string ShowMessageBox {
            get {
                return ResourceManager.GetString("ShowMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empiler deux overlays.
        /// </summary>
        internal static string ShowStackedOverlay {
            get {
                return ResourceManager.GetString("ShowStackedOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue arrière-plan. Ouvrez-en un second par-dessus..
        /// </summary>
        internal static string StackedOverlayFirstMessage {
            get {
                return ResourceManager.GetString("StackedOverlayFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier niveau.
        /// </summary>
        internal static string StackedOverlayFirstTitle {
            get {
                return ResourceManager.GetString("StackedOverlayFirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez le thème Overlay pour empiler des dialogues..
        /// </summary>
        internal static string StackedOverlayRequiresOverlayTheme {
            get {
                return ResourceManager.GetString("StackedOverlayRequiresOverlayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second: {0} ; Premier: {1}.
        /// </summary>
        internal static string StackedOverlayResultFormat {
            get {
                return ResourceManager.GetString("StackedOverlayResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue au premier plan. Fermez celui-ci puis le premier..
        /// </summary>
        internal static string StackedOverlaySecondMessage {
            get {
                return ResourceManager.GetString("StackedOverlaySecondMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuxième niveau.
        /// </summary>
        internal static string StackedOverlaySecondTitle {
            get {
                return ResourceManager.GetString("StackedOverlaySecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;opération a réussi avec succès !.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir continuer ? Cette action peut avoir des conséquences..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test des dialogues en fenêtre séparée.
        /// </summary>
        internal static string WindowDialogDescription {
            get {
                return ResourceManager.GetString("WindowDialogDescription", resourceCulture);
            }
        }
    }
}
