//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MyNet.Avalonia.Showcase.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class DialogsPageResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogsPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MyNet.Avalonia.Showcase.Resources.DialogsPageResources", typeof(DialogsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test des dialogues en overlay sur la page.
        /// </summary>
        internal static string OverlayDialogDescription {
            get {
                return ResourceManager.GetString("OverlayDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test des dialogues en fenêtre séparée.
        /// </summary>
        internal static string WindowDialogDescription {
            get {
                return ResourceManager.GetString("WindowDialogDescription", resourceCulture);
            }
        }

        internal static string ShowContentDialog {
            get {
                return ResourceManager.GetString("ShowContentDialog", resourceCulture);
            }
        }

        internal static string ShowMessageBox {
            get {
                return ResourceManager.GetString("ShowMessageBox", resourceCulture);
            }
        }

        internal static string ShowDialogBox {
            get {
                return ResourceManager.GetString("ShowDialogBox", resourceCulture);
            }
        }

        internal static string ShowStackedOverlay {
            get {
                return ResourceManager.GetString("ShowStackedOverlay", resourceCulture);
            }
        }

        internal static string CloseTopDialog {
            get {
                return ResourceManager.GetString("CloseTopDialog", resourceCulture);
            }
        }

        internal static string StackedOverlayRequiresOverlayTheme {
            get {
                return ResourceManager.GetString("StackedOverlayRequiresOverlayTheme", resourceCulture);
            }
        }

        internal static string CloseTopRequiresOverlayTheme {
            get {
                return ResourceManager.GetString("CloseTopRequiresOverlayTheme", resourceCulture);
            }
        }

        internal static string NoOpenDialog {
            get {
                return ResourceManager.GetString("NoOpenDialog", resourceCulture);
            }
        }

        internal static string DialogClosedProgrammatically {
            get {
                return ResourceManager.GetString("DialogClosedProgrammatically", resourceCulture);
            }
        }

        internal static string StackedOverlayFirstTitle {
            get {
                return ResourceManager.GetString("StackedOverlayFirstTitle", resourceCulture);
            }
        }

        internal static string StackedOverlayFirstMessage {
            get {
                return ResourceManager.GetString("StackedOverlayFirstMessage", resourceCulture);
            }
        }

        internal static string StackedOverlaySecondTitle {
            get {
                return ResourceManager.GetString("StackedOverlaySecondTitle", resourceCulture);
            }
        }

        internal static string StackedOverlaySecondMessage {
            get {
                return ResourceManager.GetString("StackedOverlaySecondMessage", resourceCulture);
            }
        }

        internal static string StackedOverlayResultFormat {
            get {
                return ResourceManager.GetString("StackedOverlayResultFormat", resourceCulture);
            }
        }
    }
}
