//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce que fournit MyNet.
        /// </summary>
        internal static string CapabilitiesSection {
            get {
                return ResourceManager.GetString("CapabilitiesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack UI complet au-delà des contrôles : thème, navigation, validation, globalisation et playground interactif..
        /// </summary>
        internal static string CapabilitiesSectionDescription {
            get {
                return ResourceManager.GetString("CapabilitiesSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modales, overlays, toasts, busy et barres de progression..
        /// </summary>
        internal static string CapabilityFeedbackDescription {
            get {
                return ResourceManager.GetString("CapabilityFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs &amp; notifications.
        /// </summary>
        internal static string CapabilityFeedbackTitle {
            get {
                return ResourceManager.GetString("CapabilityFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources .resx, formats et inflexions pour FR / EN..
        /// </summary>
        internal static string CapabilityGlobalizationDescription {
            get {
                return ResourceManager.GetString("CapabilityGlobalizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalisation.
        /// </summary>
        internal static string CapabilityGlobalizationTitle {
            get {
                return ResourceManager.GetString("CapabilityGlobalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentPage, onglets, tiroirs, historique et menus hiérarchiques..
        /// </summary>
        internal static string CapabilityNavigationDescription {
            get {
                return ResourceManager.GetString("CapabilityNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation &amp; shell.
        /// </summary>
        internal static string CapabilityNavigationTitle {
            get {
                return ResourceManager.GetString("CapabilityNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustez variantes, tailles et rôles sur chaque page de contrôle..
        /// </summary>
        internal static string CapabilityPlaygroundDescription {
            get {
                return ResourceManager.GetString("CapabilityPlaygroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playground.
        /// </summary>
        internal static string CapabilityPlaygroundTitle {
            get {
                return ResourceManager.GetString("CapabilityPlaygroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette dynamique, brushes sémantiques et variantes clair / sombre..
        /// </summary>
        internal static string CapabilityThemeDescription {
            get {
                return ResourceManager.GetString("CapabilityThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème &amp; design tokens.
        /// </summary>
        internal static string CapabilityThemeTitle {
            get {
                return ResourceManager.GetString("CapabilityThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentValidation intégré aux ViewModels et messages localisés..
        /// </summary>
        internal static string CapabilityValidationDescription {
            get {
                return ResourceManager.GetString("CapabilityValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string CapabilityValidationTitle {
            get {
                return ResourceManager.GetString("CapabilityValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories des contrôles.
        /// </summary>
        internal static string CategoriesSection {
            get {
                return ResourceManager.GetString("CategoriesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorez le catalogue par famille — le badge indique le nombre de pages de démo..
        /// </summary>
        internal static string CategoriesSectionDescription {
            get {
                return ResourceManager.GetString("CategoriesSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutons, liens, menus déroulants.
        /// </summary>
        internal static string CategoryButtonsDescription {
            get {
                return ResourceManager.GetString("CategoryButtonsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander, onglets, formulaires, bannières.
        /// </summary>
        internal static string CategoryContainersDescription {
            get {
                return ResourceManager.GetString("CategoryContainersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid, listes, arborescence.
        /// </summary>
        internal static string CategoryDataDescription {
            get {
                return ResourceManager.GetString("CategoryDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogues, notifications, progression.
        /// </summary>
        internal static string CategoryDialogsDescription {
            get {
                return ResourceManager.GetString("CategoryDialogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs, sliders, calendrier, horloge.
        /// </summary>
        internal static string CategoryInputsDescription {
            get {
                return ResourceManager.GetString("CategoryInputsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationPage, menus, pagination.
        /// </summary>
        internal static string CategoryNavigationDescription {
            get {
                return ResourceManager.GetString("CategoryNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases à cocher, radios, bascules.
        /// </summary>
        internal static string CategorySelectionDescription {
            get {
                return ResourceManager.GetString("CategorySelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordures, ellipses, icônes étendues.
        /// </summary>
        internal static string CategoryShapesDescription {
            get {
                return ResourceManager.GetString("CategoryShapesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label, TextBlock, texte sélectionnable.
        /// </summary>
        internal static string CategoryTextsDescription {
            get {
                return ResourceManager.GetString("CategoryTextsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer le showcase.
        /// </summary>
        internal static string ExploreSection {
            get {
                return ResourceManager.GetString("ExploreSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelques raccourcis pour tirer le meilleur parti de cette application..
        /// </summary>
        internal static string ExploreSectionDescription {
            get {
                return ResourceManager.GetString("ExploreSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le menu regroupe 9 familles couvrant l’ensemble du catalogue MyNet..
        /// </summary>
        internal static string ExploreTipMenu {
            get {
                return ResourceManager.GetString("ExploreTipMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur les pages de contrôles, onglet Playground pour tester styles et tailles..
        /// </summary>
        internal static string ExploreTipPlayground {
            get {
                return ResourceManager.GetString("ExploreTipPlayground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisez la recherche du menu latéral pour trouver une page par nom..
        /// </summary>
        internal static string ExploreTipSearch {
            get {
                return ResourceManager.GetString("ExploreTipSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Thème : personnalisez primaire, accent et variantes en direct..
        /// </summary>
        internal static string ExploreTipTheme {
            get {
                return ResourceManager.GetString("ExploreTipTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs fenêtre et overlay, toasts, busy.
        /// </summary>
        internal static string FeaturedDialogsDescription {
            get {
                return ResourceManager.GetString("FeaturedDialogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire MyNet.Form avec FluentValidation.
        /// </summary>
        internal static string FeaturedFormDescription {
            get {
                return ResourceManager.GetString("FeaturedFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire.
        /// </summary>
        internal static string FeaturedFormTitle {
            get {
                return ResourceManager.GetString("FeaturedFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Material Icons avec recherche et pagination.
        /// </summary>
        internal static string FeaturedIconsDescription {
            get {
                return ResourceManager.GetString("FeaturedIconsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrage rapide.
        /// </summary>
        internal static string FeaturedSection {
            get {
                return ResourceManager.GetString("FeaturedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcours recommandés pour découvrir le thème, les icônes, les formulaires et les retours utilisateur..
        /// </summary>
        internal static string FeaturedSectionDescription {
            get {
                return ResourceManager.GetString("FeaturedSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette, brushes et rôles de thème.
        /// </summary>
        internal static string FeaturedThemeDescription {
            get {
                return ResourceManager.GetString("FeaturedThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brancher MyNet dans votre app.
        /// </summary>
        internal static string GettingStartedSection {
            get {
                return ResourceManager.GetString("GettingStartedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intégrez MyNet dans une application Avalonia existante ou nouvelle..
        /// </summary>
        internal static string GettingStartedSectionDescription {
            get {
                return ResourceManager.GetString("GettingStartedSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référencer MyNet.Observable, MyNet.UI, MyNet.Globalization et les packages MyNet.Avalonia.*.
        /// </summary>
        internal static string GettingStartedStep1 {
            get {
                return ResourceManager.GetString("GettingStartedStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans Application.Styles : &lt;my:MyTheme /&gt; puis &lt;my:ThemeControlsCatalog /&gt; (voir README du showcase).
        /// </summary>
        internal static string GettingStartedStep2 {
            get {
                return ResourceManager.GetString("GettingStartedStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurer la DI via AppComposition (globalization → extended → shell, voir README).
        /// </summary>
        internal static string GettingStartedStep3 {
            get {
                return ResourceManager.GetString("GettingStartedStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser INavigationClient pour les pages et ICommandFactory pour les commandes.
        /// </summary>
        internal static string GettingStartedStep4 {
            get {
                return ResourceManager.GetString("GettingStartedStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur les ViewModels de formulaire : this.UseValidation(validator) + ValidationLocalization.Configure().
        /// </summary>
        internal static string GettingStartedStep5 {
            get {
                return ResourceManager.GetString("GettingStartedStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avalonia 12.
        /// </summary>
        internal static string HeroTagAvalonia {
            get {
                return ResourceManager.GetString("HeroTagAvalonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentValidation.
        /// </summary>
        internal static string HeroTagFluentValidation {
            get {
                return ResourceManager.GetString("HeroTagFluentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Icons.
        /// </summary>
        internal static string HeroTagMaterialIcons {
            get {
                return ResourceManager.GetString("HeroTagMaterialIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVVM &amp; DI.
        /// </summary>
        internal static string HeroTagMvvm {
            get {
                return ResourceManager.GetString("HeroTagMvvm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string OpenPage {
            get {
                return ResourceManager.GetString("OpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to README.
        /// </summary>
        internal static string ResourceReadme {
            get {
                return ResourceManager.GetString("ResourceReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string ResourceRepository {
            get {
                return ResourceManager.GetString("ResourceRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources.
        /// </summary>
        internal static string ResourcesSection {
            get {
                return ResourceManager.GetString("ResourcesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        internal static string StatCategoriesLabel {
            get {
                return ResourceManager.GetString("StatCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages de démo.
        /// </summary>
        internal static string StatDemoPagesLabel {
            get {
                return ResourceManager.GetString("StatDemoPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icônes Material.
        /// </summary>
        internal static string StatMaterialIconsLabel {
            get {
                return ResourceManager.GetString("StatMaterialIconsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages NuGet.
        /// </summary>
        internal static string StatPackagesLabel {
            get {
                return ResourceManager.GetString("StatPackagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application de référence pour explorer les contrôles, le thème MyNet et les services UI (navigation, validation, dialogs)..
        /// </summary>
        internal static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans My .NET Avalonia.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
