//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutons, cases, interrupteurs.
        /// </summary>
        internal static string CategoryButtonsDescription {
            get {
                return ResourceManager.GetString("CategoryButtonsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartes, onglets, formulaires, bannières.
        /// </summary>
        internal static string CategoryContainersDescription {
            get {
                return ResourceManager.GetString("CategoryContainersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid, listes, arborescence.
        /// </summary>
        internal static string CategoryDataDescription {
            get {
                return ResourceManager.GetString("CategoryDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs, notifications, barres de progression.
        /// </summary>
        internal static string CategoryDialogsDescription {
            get {
                return ResourceManager.GetString("CategoryDialogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs, sliders, calendrier, horloge.
        /// </summary>
        internal static string CategoryInputsDescription {
            get {
                return ResourceManager.GetString("CategoryInputsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationPage, menus, pagination.
        /// </summary>
        internal static string CategoryNavigationDescription {
            get {
                return ResourceManager.GetString("CategoryNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordures, ellipses, icônes étendues.
        /// </summary>
        internal static string CategoryShapesDescription {
            get {
                return ResourceManager.GetString("CategoryShapesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label, TextBlock, texte sélectionnable.
        /// </summary>
        internal static string CategoryTextsDescription {
            get {
                return ResourceManager.GetString("CategoryTextsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs fenêtre et overlay, toasts, busy.
        /// </summary>
        internal static string FeaturedDialogsDescription {
            get {
                return ResourceManager.GetString("FeaturedDialogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire MyNet.Form avec FluentValidation.
        /// </summary>
        internal static string FeaturedFormDescription {
            get {
                return ResourceManager.GetString("FeaturedFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire.
        /// </summary>
        internal static string FeaturedFormTitle {
            get {
                return ResourceManager.GetString("FeaturedFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Material Icons avec recherche et pagination.
        /// </summary>
        internal static string FeaturedIconsDescription {
            get {
                return ResourceManager.GetString("FeaturedIconsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrage rapide.
        /// </summary>
        internal static string FeaturedSection {
            get {
                return ResourceManager.GetString("FeaturedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette, brushes et rôles de thème.
        /// </summary>
        internal static string FeaturedThemeDescription {
            get {
                return ResourceManager.GetString("FeaturedThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brancher MyNet dans votre app.
        /// </summary>
        internal static string GettingStartedSection {
            get {
                return ResourceManager.GetString("GettingStartedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référencer MyNet.Observable, MyNet.UI, MyNet.Globalization et les packages MyNet.Avalonia.*.
        /// </summary>
        internal static string GettingStartedStep1 {
            get {
                return ResourceManager.GetString("GettingStartedStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appeler ThemeControlsHost.Register() puis ajouter &lt;my:MyTheme /&gt; dans Application.Styles.
        /// </summary>
        internal static string GettingStartedStep2 {
            get {
                return ResourceManager.GetString("GettingStartedStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer la DI : globalization → controls → extended → navigation → shell (voir README du showcase).
        /// </summary>
        internal static string GettingStartedStep3 {
            get {
                return ResourceManager.GetString("GettingStartedStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser INavigationClient pour les pages et ICommandFactory pour les commandes.
        /// </summary>
        internal static string GettingStartedStep4 {
            get {
                return ResourceManager.GetString("GettingStartedStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur les ViewModels de formulaire : this.UseValidation(validator) + ValidationLocalization.Configure().
        /// </summary>
        internal static string GettingStartedStep5 {
            get {
                return ResourceManager.GetString("GettingStartedStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string OpenPage {
            get {
                return ResourceManager.GetString("OpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rer {
            get {
                return ResourceManager.GetString("rer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application de référence pour explorer les contrôles, le thème MyNet et les services UI (navigation, validation, dialogs)..
        /// </summary>
        internal static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans MyNet Avalonia Showcase.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
