//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.MenuResources", typeof(MenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        internal static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeau.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordure.
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutons et actions.
        /// </summary>
        internal static string ButtonsAndActions {
            get {
                return ResourceManager.GetString("ButtonsAndActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton avec indicateur.
        /// </summary>
        internal static string ButtonSpinner {
            get {
                return ResourceManager.GetString("ButtonSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélecteur de plage de dates.
        /// </summary>
        internal static string DateRangePicker {
            get {
                return ResourceManager.GetString("DateRangePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrousel.
        /// </summary>
        internal static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page carrousel.
        /// </summary>
        internal static string CarouselPage {
            get {
                return ResourceManager.GetString("CarouselPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case à cocher.
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horloge.
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélecteur d&apos;horloge.
        /// </summary>
        internal static string ClockSelector {
            get {
                return ResourceManager.GetString("ClockSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélecteur de couleur.
        /// </summary>
        internal static string ColorView {
            get {
                return ResourceManager.GetString("ColorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composants.
        /// </summary>
        internal static string ComponentsCatalog {
            get {
                return ResourceManager.GetString("ComponentsCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page de contenu.
        /// </summary>
        internal static string ContentPage {
            get {
                return ResourceManager.GetString("ContentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données et listes.
        /// </summary>
        internal static string DataAndLists {
            get {
                return ResourceManager.GetString("DataAndLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grille de données.
        /// </summary>
        internal static string DataGrid {
            get {
                return ResourceManager.GetString("DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiroir.
        /// </summary>
        internal static string DrawerPage {
            get {
                return ResourceManager.GetString("DrawerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton déroulant.
        /// </summary>
        internal static string DropDownButton {
            get {
                return ResourceManager.GetString("DropDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat vide.
        /// </summary>
        internal static string EmptyState {
            get {
                return ResourceManager.GetString("EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        internal static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône étendue.
        /// </summary>
        internal static string ExtendedIcon {
            get {
                return ResourceManager.GetString("ExtendedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retours utilisateur.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séparateur de grille.
        /// </summary>
        internal static string GridSplitter {
            get {
                return ResourceManager.GetString("GridSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle avec en-tête.
        /// </summary>
        internal static string HeaderedContentControl {
            get {
                return ResourceManager.GetString("HeaderedContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien.
        /// </summary>
        internal static string HyperLinkButton {
            get {
                return ResourceManager.GetString("HyperLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle icône + contenu.
        /// </summary>
        internal static string IconContentControl {
            get {
                return ResourceManager.GetString("IconContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icônes.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrées.
        /// </summary>
        internal static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étiquette.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise en page.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string ListBox {
            get {
                return ResourceManager.GetString("ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône Material.
        /// </summary>
        internal static string MaterialIcon {
            get {
                return ResourceManager.GetString("MaterialIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu de navigation.
        /// </summary>
        internal static string NavigationMenu {
            get {
                return ResourceManager.GetString("NavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination.
        /// </summary>
        internal static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône vectorielle.
        /// </summary>
        internal static string PathIcon {
            get {
                return ResourceManager.GetString("PathIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre de progression.
        /// </summary>
        internal static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton radio.
        /// </summary>
        internal static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripple.
        /// </summary>
        internal static string Ripple {
            get {
                return ResourceManager.GetString("Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte sélectionnable.
        /// </summary>
        internal static string SelectableTextBlock {
            get {
                return ResourceManager.GetString("SelectableTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formes et dessin.
        /// </summary>
        internal static string ShapesAndDrawing {
            get {
                return ResourceManager.GetString("ShapesAndDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell et navigation.
        /// </summary>
        internal static string ShellNavigation {
            get {
                return ResourceManager.GetString("ShellNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démo.
        /// </summary>
        internal static string Showcase {
            get {
                return ResourceManager.GetString("Showcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curseur.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton partagé.
        /// </summary>
        internal static string SplitButton {
            get {
                return ResourceManager.GetString("SplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue partagée.
        /// </summary>
        internal static string SplitView {
            get {
                return ResourceManager.GetString("SplitView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page à onglets.
        /// </summary>
        internal static string TabbedPage {
            get {
                return ResourceManager.GetString("TabbedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglets.
        /// </summary>
        internal static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloc de texte.
        /// </summary>
        internal static string TextBlock {
            get {
                return ResourceManager.GetString("TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome de champ.
        /// </summary>
        internal static string TextField {
            get {
                return ResourceManager.GetString("TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue horaire.
        /// </summary>
        internal static string TimeRangePicker {
            get {
                return ResourceManager.GetString("TimeRangePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue horaire.
        /// </summary>
        internal static string TimeView {
            get {
                return ResourceManager.GetString("TimeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton basculant.
        /// </summary>
        internal static string ToggleButton {
            get {
                return ResourceManager.GetString("ToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton partagé basculant.
        /// </summary>
        internal static string ToggleSplitButton {
            get {
                return ResourceManager.GetString("ToggleSplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupteur.
        /// </summary>
        internal static string ToggleSwitch {
            get {
                return ResourceManager.GetString("ToggleSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arborescence.
        /// </summary>
        internal static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typographie.
        /// </summary>
        internal static string Typography {
            get {
                return ResourceManager.GetString("Typography", resourceCulture);
            }
        }
    }
}
