//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.Avalonia.Showcase.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer OnClick.
        /// </summary>
        internal static string ActivateOnClick {
            get {
                return ResourceManager.GetString("ActivateOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer OnClose.
        /// </summary>
        internal static string ActivateOnClose {
            get {
                return ResourceManager.GetString("ActivateOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection d&apos;une plage.
        /// </summary>
        internal static string AllowTapRangeSelection {
            get {
                return ResourceManager.GetString("AllowTapRangeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doublons autorisés.
        /// </summary>
        internal static string AllowDuplicates {
            get {
                return ResourceManager.GetString("AllowDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition des boutons.
        /// </summary>
        internal static string ButtonsLayout {
            get {
                return ResourceManager.GetString("ButtonsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position des boutons.
        /// </summary>
        internal static string ButtonsPosition {
            get {
                return ResourceManager.GetString("ButtonsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par défaut.
        /// </summary>
        internal static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple intervalles de date.
        /// </summary>
        internal static string CalendarSelectionModeMultipleRange {
            get {
                return ResourceManager.GetString("CalendarSelectionModeMultipleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string CalendarSelectionModeNone {
            get {
                return ResourceManager.GetString("CalendarSelectionModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date unique.
        /// </summary>
        internal static string CalendarSelectionModeSingleDate {
            get {
                return ResourceManager.GetString("CalendarSelectionModeSingleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalle de dates.
        /// </summary>
        internal static string CalendarSelectionModeSingleRange {
            get {
                return ResourceManager.GetString("CalendarSelectionModeSingleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplaçable.
        /// </summary>
        internal static string CanDragMove {
            get {
                return ResourceManager.GetString("CanDragMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionnable.
        /// </summary>
        internal static string CanResize {
            get {
                return ResourceManager.GetString("CanResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réordonner.
        /// </summary>
        internal static string CanUserReorderColumns {
            get {
                return ResourceManager.GetString("CanUserReorderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionner.
        /// </summary>
        internal static string CanUserResizeColumns {
            get {
                return ResourceManager.GetString("CanUserResizeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier.
        /// </summary>
        internal static string CanUserSortColumns {
            get {
                return ResourceManager.GetString("CanUserSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratégie de fermeture.
        /// </summary>
        internal static string ClosingStrategy {
            get {
                return ResourceManager.GetString("ClosingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur refermée.
        /// </summary>
        internal static string CollapseWidth {
            get {
                return ResourceManager.GetString("CollapseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonnes.
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulaire.
        /// </summary>
        internal static string ColorSpectrumShapeBox {
            get {
                return ResourceManager.GetString("ColorSpectrumShapeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulaire.
        /// </summary>
        internal static string ColorSpectrumShapeRing {
            get {
                return ResourceManager.GetString("ColorSpectrumShapeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonnes.
        /// </summary>
        internal static string Columnar {
            get {
                return ResourceManager.GetString("Columnar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur des entêtes de colonne.
        /// </summary>
        internal static string ColumnHeaderHeight {
            get {
                return ResourceManager.GetString("ColumnHeaderHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur du volet fermé.
        /// </summary>
        internal static string CompactPaneLength {
            get {
                return ResourceManager.GetString("CompactPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composantes.
        /// </summary>
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à gauche.
        /// </summary>
        internal static string CornerPositionBottomLeft {
            get {
                return ResourceManager.GetString("CornerPositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à droite.
        /// </summary>
        internal static string CornerPositionBottomRight {
            get {
                return ResourceManager.GetString("CornerPositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à gauche.
        /// </summary>
        internal static string CornerPositionTopLeft {
            get {
                return ResourceManager.GetString("CornerPositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à droite.
        /// </summary>
        internal static string CornerPositionTopRight {
            get {
                return ResourceManager.GetString("CornerPositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôle(s) personnalisé(s).
        /// </summary>
        internal static string CustomControls {
            get {
                return ResourceManager.GetString("CustomControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs foncées.
        /// </summary>
        internal static string DarkColorPalette {
            get {
                return ResourceManager.GetString("DarkColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes.
        /// </summary>
        internal static string DataGridGridLinesVisibilityAll {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string DataGridGridLinesVisibilityHorizontal {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string DataGridGridLinesVisibilityNone {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string DataGridGridLinesVisibilityVertical {
            get {
                return ResourceManager.GetString("DataGridGridLinesVisibilityVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        internal static string DataGridHeadersVisibilityAll {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonne.
        /// </summary>
        internal static string DataGridHeadersVisibilityColumn {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string DataGridHeadersVisibilityNone {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        internal static string DataGridHeadersVisibilityRow {
            get {
                return ResourceManager.GetString("DataGridHeadersVisibilityRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etendu.
        /// </summary>
        internal static string DataGridSelectionModeExtended {
            get {
                return ResourceManager.GetString("DataGridSelectionModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string DataGridSelectionModeSingle {
            get {
                return ResourceManager.GetString("DataGridSelectionModeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le jour.
        /// </summary>
        internal static string DayVisible {
            get {
                return ResourceManager.GetString("DayVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème par défaut.
        /// </summary>
        internal static string DefaultTheme {
            get {
                return ResourceManager.GetString("DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée d&apos;affichage.
        /// </summary>
        internal static string DisplayDuration {
            get {
                return ResourceManager.GetString("DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode d&apos;affichage.
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Dots {
            get {
                return ResourceManager.GetString("Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position du curseur.
        /// </summary>
        internal static string DropDownPlacement {
            get {
                return ResourceManager.GetString("DropDownPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicateur.
        /// </summary>
        internal static string ErrorGlyph {
            get {
                return ResourceManager.GetString("ErrorGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string ErrorNone {
            get {
                return ResourceManager.GetString("ErrorNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        internal static string ErrorToolTip {
            get {
                return ResourceManager.GetString("ErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur étendue.
        /// </summary>
        internal static string ExpandWidth {
            get {
                return ResourceManager.GetString("ExpandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs plates.
        /// </summary>
        internal static string FlatColorPalette {
            get {
                return ResourceManager.GetString("FlatColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demi-couleurs plates.
        /// </summary>
        internal static string FlatHalfColorPalette {
            get {
                return ResourceManager.GetString("FlatHalfColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs fluent.
        /// </summary>
        internal static string FluentColorPalette {
            get {
                return ResourceManager.GetString("FluentColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif au survol.
        /// </summary>
        internal static string FreezeOnMouseEnter {
            get {
                return ResourceManager.GetString("FreezeOnMouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de colonnes figées.
        /// </summary>
        internal static string FrozenColumnCount {
            get {
                return ResourceManager.GetString("FrozenColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plein écran.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les lignes.
        /// </summary>
        internal static string GridLinesVisibility {
            get {
                return ResourceManager.GetString("GridLinesVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiguilles.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de l&apos;entête.
        /// </summary>
        internal static string HeaderPosition {
            get {
                return ResourceManager.GetString("HeaderPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entêtes.
        /// </summary>
        internal static string HeadersVisibility {
            get {
                return ResourceManager.GetString("HeadersVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher une icône.
        /// </summary>
        internal static string IconDescription {
            get {
                return ResourceManager.GetString("IconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les variations.
        /// </summary>
        internal static string IsAccentColorsVisible {
            get {
                return ResourceManager.GetString("IsAccentColorsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est actif.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la transparence.
        /// </summary>
        internal static string IsAlphaVisible {
            get {
                return ResourceManager.GetString("IsAlphaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton &quot;Retour&quot; visible.
        /// </summary>
        internal static string IsBackButtonVisible {
            get {
                return ResourceManager.GetString("IsBackButtonVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement libellé.
        /// </summary>
        internal static string LabelAlignment {
            get {
                return ResourceManager.GetString("LabelAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est centré.
        /// </summary>
        internal static string IsCentered {
            get {
                return ResourceManager.GetString("IsCentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher TSV.
        /// </summary>
        internal static string IsColorModelVisible {
            get {
                return ResourceManager.GetString("IsColorModelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;aperçu.
        /// </summary>
        internal static string IsColorPreviewVisible {
            get {
                return ResourceManager.GetString("IsColorPreviewVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la saturation.
        /// </summary>
        internal static string IsColorSpectrumSliderVisible {
            get {
                return ResourceManager.GetString("IsColorSpectrumSliderVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser la direction.
        /// </summary>
        internal static string IsDirectionReversed {
            get {
                return ResourceManager.GetString("IsDirectionReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est éditable.
        /// </summary>
        internal static string IsEditable {
            get {
                return ResourceManager.GetString("IsEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flottant.
        /// </summary>
        internal static string IsFloating {
            get {
                return ResourceManager.GetString("IsFloating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;hexa.
        /// </summary>
        internal static string IsHexInputVisible {
            get {
                return ResourceManager.GetString("IsHexInputVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est infini.
        /// </summary>
        internal static string IsIndeterminate {
            get {
                return ResourceManager.GetString("IsIndeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volet ouvert.
        /// </summary>
        internal static string IsPaneOpen {
            get {
                return ResourceManager.GetString("IsPaneOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est un mot de passe.
        /// </summary>
        internal static string IsPassword {
            get {
                return ResourceManager.GetString("IsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture seule.
        /// </summary>
        internal static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est rond.
        /// </summary>
        internal static string IsRounded {
            get {
                return ResourceManager.GetString("IsRounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est fluide.
        /// </summary>
        internal static string IsSmooth {
            get {
                return ResourceManager.GetString("IsSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrondir la valeur.
        /// </summary>
        internal static string IsSnapToTickEnabled {
            get {
                return ResourceManager.GetString("IsSnapToTickEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôle des éléments.
        /// </summary>
        internal static string ItemsRole {
            get {
                return ResourceManager.GetString("ItemsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôles des éléments.
        /// </summary>
        internal static string ItemsRoles {
            get {
                return ResourceManager.GetString("ItemsRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs claires.
        /// </summary>
        internal static string LightColorPalette {
            get {
                return ResourceManager.GetString("LightColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignes.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure courante.
        /// </summary>
        internal static string LiveUpdate {
            get {
                return ResourceManager.GetString("LiveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauche.
        /// </summary>
        internal static string LocationLeft {
            get {
                return ResourceManager.GetString("LocationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droite.
        /// </summary>
        internal static string LocationRight {
            get {
                return ResourceManager.GetString("LocationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportement perte focus.
        /// </summary>
        internal static string LostFocusBehavior {
            get {
                return ResourceManager.GetString("LostFocusBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs Material.
        /// </summary>
        internal static string MaterialColorPalette {
            get {
                return ResourceManager.GetString("MaterialColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demi-couleurs Material.
        /// </summary>
        internal static string MaterialHalfColorPalette {
            get {
                return ResourceManager.GetString("MaterialHalfColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre max..
        /// </summary>
        internal static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur max. liste.
        /// </summary>
        internal static string MaxDropDownHeight {
            get {
                return ResourceManager.GetString("MaxDropDownHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eléments maximum.
        /// </summary>
        internal static string MaxItems {
            get {
                return ResourceManager.GetString("MaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le mois.
        /// </summary>
        internal static string MonthVisible {
            get {
                return ResourceManager.GetString("MonthVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas afficher.
        /// </summary>
        internal static string NoDisplay {
            get {
                return ResourceManager.GetString("NoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numérique.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décalage horizontal.
        /// </summary>
        internal static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décalage vertical.
        /// </summary>
        internal static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacité.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur du volet ouvert.
        /// </summary>
        internal static string OpenPaneLength {
            get {
                return ResourceManager.GetString("OpenPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string OrientationHorizontal {
            get {
                return ResourceManager.GetString("OrientationHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string OrientationVertical {
            get {
                return ResourceManager.GetString("OrientationVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        internal static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette - Colonnes.
        /// </summary>
        internal static string PaletteColumnCount {
            get {
                return ResourceManager.GetString("PaletteColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démonstration.
        /// </summary>
        internal static string Playground {
            get {
                return ResourceManager.GetString("Playground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la page.
        /// </summary>
        internal static string PopPage {
            get {
                return ResourceManager.GetString("PopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de la popup.
        /// </summary>
        internal static string PopupPlacement {
            get {
                return ResourceManager.GetString("PopupPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préfixe.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string PrefixDescription {
            get {
                return ResourceManager.GetString("PrefixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévisualisation.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle page.
        /// </summary>
        internal static string PushPage {
            get {
                return ResourceManager.GetString("PushPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aléatoire.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône aléatoire.
        /// </summary>
        internal static string RandomIcon {
            get {
                return ResourceManager.GetString("RandomIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droite.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur des entêtes de ligne.
        /// </summary>
        internal static string RowHeaderWidth {
            get {
                return ResourceManager.GetString("RowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur de ligne.
        /// </summary>
        internal static string RowHeight {
            get {
                return ResourceManager.GetString("RowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondes.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de sélection.
        /// </summary>
        internal static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toujours sélectionné.
        /// </summary>
        internal static string SelectionModeAlwaysSelected {
            get {
                return ResourceManager.GetString("SelectionModeAlwaysSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        internal static string SelectionModeMultiple {
            get {
                return ResourceManager.GetString("SelectionModeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string SelectionModeSingle {
            get {
                return ResourceManager.GetString("SelectionModeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string SelectionModeToggle {
            get {
                return ResourceManager.GetString("SelectionModeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séparateur.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forme.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formes.
        /// </summary>
        internal static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le fond.
        /// </summary>
        internal static string ShowBackground {
            get {
                return ResourceManager.GetString("ShowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les boutons.
        /// </summary>
        internal static string ShowButtons {
            get {
                return ResourceManager.GetString("ShowButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection de la cellule.
        /// </summary>
        internal static string ShowCellSelection {
            get {
                return ResourceManager.GetString("ShowCellSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le bouton &quot;Effacer&quot;.
        /// </summary>
        internal static string ShowClearButton {
            get {
                return ResourceManager.GetString("ShowClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le presse papier.
        /// </summary>
        internal static string ShowClipboardButton {
            get {
                return ResourceManager.GetString("ShowClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le bouton Fermer.
        /// </summary>
        internal static string ShowCloseButton {
            get {
                return ResourceManager.GetString("ShowCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher une erreur.
        /// </summary>
        internal static string ShowError {
            get {
                return ResourceManager.GetString("ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;image.
        /// </summary>
        internal static string ShowImage {
            get {
                return ResourceManager.GetString("ShowImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la taille de la page.
        /// </summary>
        internal static string ShowPageSizeSelector {
            get {
                return ResourceManager.GetString("ShowPageSizeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le filigrane.
        /// </summary>
        internal static string ShowPlaceholderText {
            get {
                return ResourceManager.GetString("ShowPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le saut rapide.
        /// </summary>
        internal static string ShowQuickJump {
            get {
                return ResourceManager.GetString("ShowQuickJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la sélection.
        /// </summary>
        internal static string ShowSelection {
            get {
                return ResourceManager.GetString("ShowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout sélectionner.
        /// </summary>
        internal static string ShowSelectAll {
            get {
                return ResourceManager.GetString("ShowSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la valeur.
        /// </summary>
        internal static string ShowValue {
            get {
                return ResourceManager.GetString("ShowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la valeur.
        /// </summary>
        internal static string ShowValueOnMouseOver {
            get {
                return ResourceManager.GetString("ShowValueOnMouseOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 couleurs.
        /// </summary>
        internal static string SixteenColorPalette {
            get {
                return ResourceManager.GetString("SixteenColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        internal static string SizeMultiplier {
            get {
                return ResourceManager.GetString("SizeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailles.
        /// </summary>
        internal static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacement.
        /// </summary>
        internal static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectre.
        /// </summary>
        internal static string Spectrum {
            get {
                return ResourceManager.GetString("Spectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string SpinnerLayoutHorizontal {
            get {
                return ResourceManager.GetString("SpinnerLayoutHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposé.
        /// </summary>
        internal static string SpinnerLayoutOpposite {
            get {
                return ResourceManager.GetString("SpinnerLayoutOpposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string SpinnerLayoutVertical {
            get {
                return ResourceManager.GetString("SpinnerLayoutVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        internal static string SplitViewDisplayModeCompactInline {
            get {
                return ResourceManager.GetString("SplitViewDisplayModeCompactInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact recouvert.
        /// </summary>
        internal static string SplitViewDisplayModeCompactOverlay {
            get {
                return ResourceManager.GetString("SplitViewDisplayModeCompactOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ligne.
        /// </summary>
        internal static string SplitViewDisplayModeInline {
            get {
                return ResourceManager.GetString("SplitViewDisplayModeInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recouvert.
        /// </summary>
        internal static string SplitViewDisplayModeOverlay {
            get {
                return ResourceManager.GetString("SplitViewDisplayModeOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs standards.
        /// </summary>
        internal static string StandardColorPalette {
            get {
                return ResourceManager.GetString("StandardColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation des sous menus.
        /// </summary>
        internal static string SubMenuIndent {
            get {
                return ResourceManager.GetString("SubMenuIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffixe.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string SuffixDescription {
            get {
                return ResourceManager.GetString("SuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser les boutons.
        /// </summary>
        internal static string SwitchButtons {
            get {
                return ResourceManager.GetString("SwitchButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onglets.
        /// </summary>
        internal static string Tabs {
            get {
                return ResourceManager.GetString("Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le texte suivant.
        /// </summary>
        internal static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thèmes.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence des graduations.
        /// </summary>
        internal static string TickFrequency {
            get {
                return ResourceManager.GetString("TickFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur des graduations.
        /// </summary>
        internal static string TickLength {
            get {
                return ResourceManager.GetString("TickLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de graduation.
        /// </summary>
        internal static string TickMode {
            get {
                return ResourceManager.GetString("TickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string TickModeBoth {
            get {
                return ResourceManager.GetString("TickModeBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation.
        /// </summary>
        internal static string TickModeTick {
            get {
                return ResourceManager.GetString("TickModeTick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs.
        /// </summary>
        internal static string TickModeValues {
            get {
                return ResourceManager.GetString("TickModeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement des graduations.
        /// </summary>
        internal static string TickPlacement {
            get {
                return ResourceManager.GetString("TickPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bas ou Droite.
        /// </summary>
        internal static string TickPlacementBottomRight {
            get {
                return ResourceManager.GetString("TickPlacementBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string TickPlacementNone {
            get {
                return ResourceManager.GetString("TickPlacementNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string TickPlacementOutside {
            get {
                return ResourceManager.GetString("TickPlacementOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut ou Gauche.
        /// </summary>
        internal static string TickPlacementTopLeft {
            get {
                return ResourceManager.GetString("TickPlacementTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduations.
        /// </summary>
        internal static string Ticks {
            get {
                return ResourceManager.GetString("Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        internal static string ToastClosingStrategyAutoClose {
            get {
                return ResourceManager.GetString("ToastClosingStrategyAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux.
        /// </summary>
        internal static string ToastClosingStrategyBoth {
            get {
                return ResourceManager.GetString("ToastClosingStrategyBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouton.
        /// </summary>
        internal static string ToastClosingStrategyCloseButton {
            get {
                return ResourceManager.GetString("ToastClosingStrategyCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string ToastClosingStrategyNone {
            get {
                return ResourceManager.GetString("ToastClosingStrategyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas au centre.
        /// </summary>
        internal static string ToasterPositionBottomCenter {
            get {
                return ResourceManager.GetString("ToasterPositionBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à gauche.
        /// </summary>
        internal static string ToasterPositionBottomLeft {
            get {
                return ResourceManager.GetString("ToasterPositionBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bas à droite.
        /// </summary>
        internal static string ToasterPositionBottomRight {
            get {
                return ResourceManager.GetString("ToasterPositionBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut au centre.
        /// </summary>
        internal static string ToasterPositionTopCenter {
            get {
                return ResourceManager.GetString("ToasterPositionTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à gauche.
        /// </summary>
        internal static string ToasterPositionTopLeft {
            get {
                return ResourceManager.GetString("ToasterPositionTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En haut à droite.
        /// </summary>
        internal static string ToasterPositionTopRight {
            get {
                return ResourceManager.GetString("ToasterPositionTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur.
        /// </summary>
        internal static string ToastWidth {
            get {
                return ResourceManager.GetString("ToastWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        internal static string Transition {
            get {
                return ResourceManager.GetString("Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte affiché sous le contrôle.
        /// </summary>
        internal static string UnderText {
            get {
                return ResourceManager.GetString("UnderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 caractères autorisés.
        /// </summary>
        internal static string UnderTextDescription {
            get {
                return ResourceManager.GetString("UnderTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne alternée.
        /// </summary>
        internal static string UseAlternateRowBackground {
            get {
                return ResourceManager.GetString("UseAlternateRowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer l&apos;overlay.
        /// </summary>
        internal static string UseOverlay {
            get {
                return ResourceManager.GetString("UseOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les secondes.
        /// </summary>
        internal static string UseSeconds {
            get {
                return ResourceManager.GetString("UseSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser les transitions.
        /// </summary>
        internal static string UseTransitions {
            get {
                return ResourceManager.GetString("UseTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position de la valeur.
        /// </summary>
        internal static string ValuePosition {
            get {
                return ResourceManager.GetString("ValuePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code XAML.
        /// </summary>
        internal static string XamlCode {
            get {
                return ResourceManager.GetString("XamlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher l&apos;année.
        /// </summary>
        internal static string YearVisible {
            get {
                return ResourceManager.GetString("YearVisible", resourceCulture);
            }
        }
    }
}
