//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Showcase.Resources;

using System;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class ToolBarPageResources
{
    private static System.Resources.ResourceManager? resourceMan;

    private static System.Globalization.CultureInfo? resourceCulture;

    internal ToolBarPageResources()
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new System.Resources.ResourceManager(
            "MyNet.Avalonia.Showcase.Resources.ToolBarPageResources",
            typeof(ToolBarPageResources).Assembly);

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static System.Globalization.CultureInfo Culture
    {
        get => resourceCulture!;
        set => resourceCulture = value;
    }

    internal static string ItemSpacing => ResourceManager.GetString(nameof(ItemSpacing), resourceCulture)!;

    internal static string OverflowMode => ResourceManager.GetString(nameof(OverflowMode), resourceCulture)!;

    internal static string AddItem => ResourceManager.GetString(nameof(AddItem), resourceCulture)!;

    internal static string RemoveItem => ResourceManager.GetString(nameof(RemoveItem), resourceCulture)!;

    internal static string ResetItems => ResourceManager.GetString(nameof(ResetItems), resourceCulture)!;

    internal static string PreviewWidth => ResourceManager.GetString(nameof(PreviewWidth), resourceCulture)!;

    internal static string DebugPanelTitle => ResourceManager.GetString(nameof(DebugPanelTitle), resourceCulture)!;

    internal static string IsOverflowAvailable => ResourceManager.GetString(nameof(IsOverflowAvailable), resourceCulture)!;

    internal static string OverflowItemsCount => ResourceManager.GetString(nameof(OverflowItemsCount), resourceCulture)!;

    internal static string ItemsCount => ResourceManager.GetString(nameof(ItemsCount), resourceCulture)!;

    internal static string FluentRibbonNote => ResourceManager.GetString(nameof(FluentRibbonNote), resourceCulture)!;

    internal static string PresetSmallTitle => ResourceManager.GetString(nameof(PresetSmallTitle), resourceCulture)!;

    internal static string PresetStandardTitle => ResourceManager.GetString(nameof(PresetStandardTitle), resourceCulture)!;

    internal static string PresetOverflowTitle => ResourceManager.GetString(nameof(PresetOverflowTitle), resourceCulture)!;

    internal static string PresetMixedTitle => ResourceManager.GetString(nameof(PresetMixedTitle), resourceCulture)!;
}
