<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Product>My .NET Avalonia - UI</Product>
        <PackageIcon>MyAvalonia.png</PackageIcon>
        <Description>Custom user interface components and controls for Avalonia applications, providing a rich set of features and functionality.</Description>
        <PackageTags>Avalonia;UI;Controls;MyNet;Extensions;CrossPlatform;Desktop</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyNet.Avalonia.Controls\MyNet.Avalonia.Controls.csproj" />
        <ProjectReference Include="..\MyNet.Avalonia.Theme\MyNet.Avalonia.Theme.csproj" />
        <ProjectReference Include="..\MyNet.Avalonia.Theme.Controls\MyNet.Avalonia.Theme.Controls.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MyNet.Globalization" />
      <PackageReference Include="MyNet.UI" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Themes/Generic.axaml" />
      <AvaloniaResource Include="Themes/Controls/MessageNotificationControl.axaml" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Remove="Dialogs\**" />
        <AvaloniaResource Remove="Controls\Dialogs\**" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="Dialogs\**" />
      <AvaloniaXaml Remove="Controls\Dialogs\**" />
      <AvaloniaXaml Remove="Themes\Controls\OverlayMessageBox.axaml" />
      <AvaloniaXaml Remove="Themes\Controls\WindowDialog.axaml" />
      <AvaloniaXaml Remove="Themes\Controls\WindowMessageBox.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Dialogs\**" />
      <Compile Remove="Controls\Dialogs\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Dialogs\**" />
      <EmbeddedResource Remove="Controls\Dialogs\**" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="Dialogs\**" />
      <AdditionalFiles Remove="Controls\Dialogs\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Dialogs\**" />
      <None Remove="Controls\Dialogs\**" />
    </ItemGroup>

</Project>
