<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Product>My .NET Avalonia - Performance Test</Product>
        <Description>Performance testing application for Avalonia UI with base Fluent theme.</Description>
        <NeutralLanguage>fr</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Controls\MyNet.Avalonia.Controls.csproj" />
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Theme\MyNet.Avalonia.Theme.csproj" />
        <ProjectReference Include="..\..\src\MyNet.Avalonia\MyNet.Avalonia.csproj" />
    </ItemGroup>

</Project>
