<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Headless" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
        <ApplicationDefinition Include="Infrastructure\ShowcaseTestApp.axaml" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\demos\MyNet.Avalonia.Showcase\MyNet.Avalonia.Showcase.csproj" />
    </ItemGroup>

</Project>
