//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.Avalonia.Controls.Localization;

using System;

/// <summary>
/// Localized strings for <see cref="TimeRangePickerEx"/>.
/// </summary>
public static class TimeRangePickerExResources
{
    private static global::System.Resources.ResourceManager? _resourceMan;

    private static global::System.Globalization.CultureInfo? _resourceCulture;

    public static global::System.Resources.ResourceManager ResourceManager =>
        _resourceMan ??= new global::System.Resources.ResourceManager(
            "MyNet.Avalonia.Controls.Localization.TimeRangePickerExResources",
            typeof(TimeRangePickerExResources).Assembly);

    public static global::System.Globalization.CultureInfo Culture
    {
        get => _resourceCulture ?? global::System.Globalization.CultureInfo.CurrentUICulture;
        set => _resourceCulture = value;
    }

    public static string EndBeforeStart => GetString(nameof(EndBeforeStart));

    public static string OvernightIndicatorSuffix => GetString(nameof(OvernightIndicatorSuffix));

    public static string Start => GetString(nameof(Start));

    public static string End => GetString(nameof(End));

    private static string GetString(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;
}
