<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Product>My .NET Avalonia - Performance Test</Product>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>
    <ItemGroup>
      <Content Include="config\NLog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyNet.Avalonia.PerfTest\MyNet.Avalonia.PerfTest.csproj" />
    </ItemGroup>
</Project>
