<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Product>My .NET Avalonia</Product>
        <Description>Platform for testing and experimenting with Avalonia controls and styles. </Description>
        <ApplicationIcon>Assets\Demo.ico</ApplicationIcon>
        <NeutralLanguage>fr</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="$(Configuration) == 'Debug'" />
        <PackageReference Include="Fody" PrivateAssets="all" />
        <PackageReference Include="MyNet.UI" />
        <PackageReference Include="MyNet.Utilities.Generator.Extensions" />
        <PackageReference Include="MyNet.Utilities.Geography.Extensions" />
        <PackageReference Include="MyNet.Utilities.Localization.Extensions" />
        <PackageReference Include="MyNet.Utilities.Logging.NLog" />
        <PackageReference Include="PropertyChanged.Fody" PrivateAssets="All" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Controls\MyNet.Avalonia.Controls.csproj" />
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Theme\MyNet.Avalonia.Theme.csproj" />
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Extended\MyNet.Avalonia.Extended.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\CommonResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>CommonResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\DataGridPageResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>DataGridPageResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\DialogsPageResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>DialogsPageResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\MenuPageResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>MenuPageResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\MenuResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>MenuResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\NavigationMenuPageResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>NavigationMenuPageResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\SettingsResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>SettingsResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\FormResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>FormResources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\NotificationPageResources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>NotificationPageResources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\CommonResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\DataGridPageResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>DataGridPageResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\DialogsPageResources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>DialogsPageResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\MenuPageResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>MenuPageResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\MenuResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>MenuResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\NavigationMenuPageResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>NavigationMenuPageResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\SettingsResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>SettingsResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\FormResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>FormResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\NotificationPageResources.resx">
          <Generator>ResXFileCodeGenerator</Generator>
          <LastGenOutput>NotificationPageResources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>
