<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>MyNet.Avalonia.Controls.Headless.Tests</RootNamespace>
        <OutputType>Exe</OutputType>
        <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MyNet.Avalonia.Controls\MyNet.Avalonia.Controls.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ApplicationDefinition Include="App.axaml" />
        <AvaloniaResource Include="MinimalControlThemes.axaml" />
    </ItemGroup>

</Project>
