// -----------------------------------------------------------------------
// <copyright file="ControlThemeViewModelFactory.cs" company="Stéphane ANDRE">
// Copyright (c) Stéphane ANDRE. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Linq;
using MyNet.Avalonia.Showcase.ThemeBuilder.Builders;
using MyNet.Avalonia.Showcase.ThemeBuilder.Builders.Editors;
using MyNet.Avalonia.Showcase.ThemeBuilder.Definitions;
using MyNet.Avalonia.Showcase.ThemeBuilder.Metadata;
using MyNet.Avalonia.Showcase.ThemeBuilder.Registry;
using MyNet.Avalonia.Showcase.ViewModels.Playground.Options;
using MyNet.UI.Commands;

namespace MyNet.Avalonia.Showcase.ViewModels.Playground.Factories;

/// <summary>
/// Represents a factory for creating instances of <see cref="ControlThemeViewModel"/> based on the provided <see cref="ControlThemeBuilder"/>. This factory encapsulates the logic for constructing the necessary components, such as option factories and setting factories, to create a fully configured view model for a control theme. By utilizing the builder pattern, this factory allows for flexible and modular creation of control theme view models, enabling easy customization and extension as needed in the theme builder application.
/// </summary>
/// <param name="builder">The control theme builder used to construct the view models.</param>
internal sealed class ControlThemeViewModelFactory(ControlThemeBuilder builder, ICommandFactory commands)
{
    /// <summary>
    /// Creates a new instance of the ControlThemeViewModel for the specified control name.
    /// </summary>
    /// <remarks>This method uses internal factories to generate the necessary options and settings for the
    /// control theme view model. Ensure that the provided control name is valid and corresponds to an existing
    /// control.</remarks>
    /// <param name="controlName">The name of the control for which to create the theme view model. This parameter cannot be null or empty.</param>
    /// <returns>A ControlThemeViewModel instance that contains the built control, its metadata, and the associated settings and
    /// options.</returns>
    public ControlThemeViewModel Create(string controlName)
    {
        var choiceFactory = CreateChoiceFactory();
        var optionFactory = CreateOptionFactory(choiceFactory);
        var definition = builder.Build(controlName);
        var choiceMetadata = builder.GetThemeDisplayName(controlName);
        var allOptions = definition.CustomSettings.Select(optionFactory.Create).ToList();
        var availableOptions = allOptions.Where(x => string.IsNullOrEmpty(x.Group)).Select(x => x.Option);
        var availableGroups = allOptions.Where(x => !string.IsNullOrEmpty(x.Group)).GroupBy(x => x.Group).Select(x => new GroupOptionViewModel([.. x.Select(y => y.Option)], new LocalizedString(x.Key!)));

        return new(definition, choiceMetadata.DisplayName)
        {
            AvailableVariants = [.. definition.Variants.Select(choiceFactory.Create)],
            AvailableRoles = [.. definition.Roles.Select(choiceFactory.Create)],
            AvailableShapes = [.. definition.Shapes.Select(choiceFactory.Create)],
            AvailableSizes = [.. definition.Sizes.Select(choiceFactory.Create)],
            AvailableItemsRoles = [.. definition.ItemsRoles.Select(choiceFactory.Create)],
            AvailableOptions = [.. availableOptions],
            AvailableGroups = [.. availableGroups]
        };
    }

    /// <summary>
    /// Creates a new instance of the ChoiceViewModelFactory using option metadata generated by the builder.
    /// </summary>
    /// <remarks>Use this method to obtain a ChoiceViewModelFactory that is preconfigured with the necessary
    /// option metadata for further operations.</remarks>
    /// <returns>A new ChoiceViewModelFactory initialized with the constructed option metadata.</returns>
    private ChoiceViewModelFactory CreateChoiceFactory()
    {
        var metadata = builder.BuildChoiceMetadata();

        return new(metadata);
    }

    /// <summary>
    /// Creates a new instance of the OptionViewModelFactory using the provided ChoiceViewModelFactory and setting metadata generated by the builder.
    /// </summary>
    /// <param name="optionFactory">The ChoiceViewModelFactory used to create choice view models for the options.</param>
    /// <returns>A new OptionViewModelFactory initialized with the provided ChoiceViewModelFactory and setting metadata.</returns>
    private OptionViewModelFactory CreateOptionFactory(ChoiceViewModelFactory optionFactory)
    {
        var metadata = builder.BuildOptionMetadata();
        var registry = new ControlEditorRegistry();

        RegisterDefaultEditors(registry, optionFactory, commands);

        return new(registry, metadata);
    }

    /// <summary>
    /// Registers the default control editors and definitions for various option types in the specified registry.
    /// </summary>
    /// <remarks>This method configures the registry with default editors for common control types, such as
    /// combo boxes and list boxes, ensuring that they are associated with the appropriate view models. It is typically
    /// called during application initialization to set up standard editing behaviors.</remarks>
    /// <param name="registry">The registry in which control definitions and editors are registered. This enables customization and extension
    /// of control behaviors for different option types.</param>
    /// <param name="choiceFactory">A factory used to create view models for the options defined in the registry. This facilitates the instantiation
    /// of option-related view models required by the editors.</param>
    /// <param name="commands">The command factory used to create commands for the actions. This enables the instantiation of action-related view models required by the editors.</param>
    private static void RegisterDefaultEditors(ControlEditorRegistry registry, ChoiceViewModelFactory choiceFactory, ICommandFactory commands)
    {
        // Definitions
        registry.RegisterDefinition<ControlClassDefinition>((x, y) => new ComboBoxOptionViewModel(x, [.. (y.Metadata as IChoicesEditorMetadata)?.Choices.Select(choiceFactory.Create) ?? []], y.DisplayName));
        registry.RegisterDefinition<ControlClassToggleDefinition>((x, y) => new ToggleSwitchOptionViewModel(x, y.DisplayName));
        registry.RegisterDefinition<ControlActionDefinition>((x, y) => new ButtonOptionViewModel(commands, x, y.DisplayName, y.Icon));

        // Types
        registry.Register<bool>((x, y) => new ToggleSwitchOptionViewModel(x, y.DisplayName));
        registry.Register<decimal>((x, y) => new SliderOptionViewModel(x, y.DisplayName));
        registry.Register<double>((x, y) => new SliderOptionViewModel(x, y.DisplayName));
        registry.Register<int>((x, y) => new IntSliderOptionViewModel(x, y.DisplayName));
        registry.Register<string>((x, y) => new TextBoxOptionViewModel(x, y.DisplayName));

        // Custom editors
        registry.RegisterEditor<ButtonEditorMetadata>((x, y) => new ButtonOptionViewModel(commands, (ControlActionDefinition)x, y.DisplayName, y.Icon) { Role = y.Metadata.Role });
        registry.RegisterEditor<TextBoxEditorMetadata>((x, y) => new TextBoxOptionViewModel(x, y.DisplayName));
        registry.RegisterEditor<ToggleSwitchEditorMetadata>((x, y) => new ToggleSwitchOptionViewModel(x, y.DisplayName));
        registry.RegisterEditor<ListBoxEditorMetadata>((x, y) => new ListBoxOptionViewModel(x, [.. y.Metadata.Choices.Select(choiceFactory.Create)], y.DisplayName, y.Metadata.AllowMultipleSelection));
        registry.RegisterEditor<ComboBoxEditorMetadata>((x, y) => new ComboBoxOptionViewModel(x, [.. y.Metadata.Choices.Select(choiceFactory.Create)], y.DisplayName)
        {
            AllowNullValue = y.Metadata.AllowNullValue
        });
        registry.RegisterEditor<SliderEditorMetadata>((x, y) => new SliderOptionViewModel(x, y.DisplayName)
        {
            Minimum = y.Metadata.Minimum,
            Maximum = y.Metadata.Maximum,
            Increment = y.Metadata.Increment
        });
        registry.RegisterEditor<IntSliderEditorMetadata>((x, y) => new IntSliderOptionViewModel(x, y.DisplayName)
        {
            Minimum = y.Metadata.Minimum,
            Maximum = y.Metadata.Maximum,
            Increment = y.Metadata.Increment
        });
        registry.RegisterEditor<NumericUpDownEditorMetadata>((x, y) => new NumericUpDownOptionViewModel(x, y.DisplayName)
        {
            Minimum = y.Metadata.Minimum,
            Maximum = y.Metadata.Maximum,
            Increment = y.Metadata.Increment
        });
        registry.RegisterEditor<IntNumericUpDownEditorMetadata>((x, y) => new IntNumericUpDownOptionViewModel(x, y.DisplayName)
        {
            Minimum = y.Metadata.Minimum,
            Maximum = y.Metadata.Maximum,
            Increment = y.Metadata.Increment
        });
    }
}
