name: CI - Build and Test

on:
  push:
    branches: [ "main", "feature/*", "hotfix/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: sandre58/MyWorkflows/.github/workflows/ci.yml@main
    with:
      app-projects: "demos"
      nuget-projects: "src"
      install-web-workload: true
      install-ios-workload: true
      install-android-workload: true
      install-wasm-workload: true
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}