name: Release

on:
  push:
    tags:
      - '*/v*'  # Matches tags like MyNet.Utilities/v1.2.3
  repository_dispatch:
    types: [tag_created]  # Triggered by tag.yml workflow

jobs:
  build:
    uses: sandre58/MyWorkflows/.github/workflows/release.yml@main
    with:
      install-web-workload: true
      install-ios-workload: true
      install-android-workload: true
      install-wasm-workload: true
    secrets:
      RELEASE_API_KEY: ${{ secrets.NUGET_API_KEY }}
      PRERELEASE_API_KEY: ${{ secrets.GITHUB_TOKEN }}